name: chatgpt_client
version: 1.0.0+1
publish_to: none
description: A sample ChatGPT client built with Flutter.
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  gap: ^3.0.1
  get_it: ^7.6.4
  http: ^0.13.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  markdown_widget: ^2.0.0+1
  material_segmented_control: ^5.0.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
flutter:
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
  uses-material-design: true
